#!/bin/bash
set -e
source ~/.env
export PGPASSWORD=$POSTGRES_PASSWORD  # Use postgres user password

## Create the database, schema, and roles
psql -U postgres -f create_database.sql
psql -U postgres -d prod -v TELLER_POSTGRES_PASSWORD="$TELLER_POSTGRES_PASSWORD" -f configure_database.sql

## Create all tables in dependency order
psql -U postgres -d prod -f teller_enums.sql
psql -U postgres -d prod -f teller_institution.sql
psql -U postgres -d prod -f teller_account_links.sql
#psql -U postgres -d prod -f teller_account.sql
#psql -U postgres -d prod -f teller_identity.sql
#psql -U postgres -d prod -f teller_identity_name.sql
#psql -U postgres -d prod -f teller_identity_email.sql
#psql -U postgres -d prod -f teller_identity_phone_number.sql
#psql -U postgres -d prod -f teller_identity_address_data.sql
#psql -U postgres -d prod -f teller_identity_address.sql
#psql -U postgres -d prod -f teller_account_identities.sql
#psql -U postgres -d prod -f teller_routing_numbers.sql
#psql -U postgres -d prod -f teller_account_details_links.sql
#psql -U postgres -d prod -f teller_account_details.sql
#psql -U postgres -d prod -f teller_account_balances_links.sql
#psql -U postgres -d prod -f teller_account_balances.sql
#psql -U postgres -d prod -f teller_transaction_type.sql
#psql -U postgres -d prod -f teller_transaction_details_counterparty.sql
#psql -U postgres -d prod -f teller_transaction_links.sql
#psql -U postgres -d prod -f teller_transaction_details.sql
#psql -U postgres -d prod -f teller_transaction.sql
#psql -U postgres -d prod -f create_triggers.sql
#psql -U postgres -d prod -f create_audit.sql

## Transfer ownership of all database objects to teller user
psql -U postgres -d prod -f transfer_ownership.sql

unset PGPASSWORD