#!/usr/bin/env python3

import os
import sys
from io import StringIO
from dotenv import load_dotenv
from peewee import PostgresqlDatabase
from pwiz import *


def main():
    load_dotenv()
    db = PostgresqlDatabase(
        os.getenv('POSTGRES_DB'),
        user=os.getenv('POSTGRES_USER'),
        password=os.getenv('POSTGRES_PASSWORD'),
        host=os.getenv('POSTGRES_HOST'),
        port=int(os.getenv('POSTGRES_PORT')),
        options='-c search_path=teller'
    )
    
    introspector = Introspector.from_database(db, schema='teller')
    
    buffer = StringIO()
    old_stdout = sys.stdout
    sys.stdout = buffer
    
    print_models(
        introspector,
        preserve_order=True,
        include_views=False,
        ignore_unknown=False,
        snake_case=True
    )
    
    sys.stdout = old_stdout
    output = buffer.getvalue()
    
    with open('models_autogenerated.py', 'w') as f:
        f.write(output)

if __name__ == '__main__':
    main()

