[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "teller"
version = "0.1.0"
authors = [
    { name = "Your Name" }
]
description = "Teller API Integration"
requires-python = ">=3.8"

[tool.setuptools]
py-modules = [
    "teller_client",
    "models",
    "teller_account",
    "main"
] 