CREATE TABLE teller.nys_snw_category (
    nys_snw_category_id BIGSERIAL PRIMARY KEY,
    level_1 TEXT,
    level_1_name TEXT,
    level_2 TEXT,
    level_2_name TEXT,
    level_3 TEXT,
    level_4 TEXT,
    categorization TEXT,
    applicability TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE teller.nys_snw_category IS 'NYS Statement of Net Worth category mapping table.';
COMMENT ON COLUMN teller.nys_snw_category.categorization IS 'NYS SNW category label.';
COMMENT ON COLUMN teller.nys_snw_category.applicability IS 'Applicability guidance from the source document.';
CREATE UNIQUE INDEX nys_snw_category_unique_hierarchy_idx ON teller.nys_snw_category (
    level_1, level_1_name, level_2, level_2_name, level_3, COALESCE(level_4, ''), COALESCE(categorization, ''),
    COALESCE(applicability, '')
);

INSERT INTO teller.nys_snw_category (level_1, level_1_name, level_2, level_2_name, level_3, level_4, categorization, applicability) VALUES
    ('III.', 'EXPENSES:', '(a)', 'Housing: Monthly', '1', NULL, 'Mortgage/Co-op Loan', 'N/A'),
    ('III.', 'EXPENSES:', '(a)', 'Housing: Monthly', '2', NULL, 'Home Equity Line of Credit/Second Mortgage', 'N/A'),
    ('III.', 'EXPENSES:', '(a)', 'Housing: Monthly', '3', NULL, 'Real Estate Taxes', 'N/A'),
    ('III.', 'EXPENSES:', '(a)', 'Housing: Monthly', '4', NULL, 'Homeowners/Renter’s Insurance', 'N/A'),
    ('III.', 'EXPENSES:', '(a)', 'Housing: Monthly', '5', NULL, 'Homeowner’s Association/Maintenance charges/Condominium Charges', 'N/A'),
    ('III.', 'EXPENSES:', '(a)', 'Housing: Monthly', '6', NULL, 'Rent', NULL),
    ('III.', 'EXPENSES:', '(a)', 'Housing: Monthly', '7', NULL, 'Other', 'N/A'),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '1', NULL, 'Fuel Oil/Gas', 'N/A'),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '2', NULL, 'Electric', 'N/A'),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '3', NULL, 'Telephone (land line)', 'N/A'),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '4', NULL, 'Mobile Phone', NULL),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '5', NULL, 'Cable/Satellite TV', NULL),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '6', NULL, 'Internet', NULL),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '7', NULL, 'Alarm', 'N/A'),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '8', NULL, 'Water', 'N/A'),
    ('III.', 'EXPENSES:', '(b)', 'Utilities:  Monthly', '9', NULL, 'Other', NULL),
    ('III.', 'EXPENSES:', '(c)', 'Food: Monthly', '1', NULL, 'Groceries', NULL),
    ('III.', 'EXPENSES:', '(c)', 'Food: Monthly', '2', NULL, 'Dining Out/Take Out', NULL),
    ('III.', 'EXPENSES:', '(c)', 'Food: Monthly', '3', NULL, 'Other', NULL),
    ('III.', 'EXPENSES:', '(d)', 'Clothing:  Monthly', '1', NULL, 'Yourself', NULL),
    ('III.', 'EXPENSES:', '(d)', 'Clothing:  Monthly', '2', NULL, 'Child(ren)', 'N/A'),
    ('III.', 'EXPENSES:', '(d)', 'Clothing:  Monthly', '3', NULL, 'Dry Cleaning', NULL),
    ('III.', 'EXPENSES:', '(d)', 'Clothing:  Monthly', '4', NULL, 'Other', NULL),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '1', NULL, 'Life', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '2', NULL, 'Fire, theft and liability and personal articles policy', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '3', NULL, 'Automotive', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '4', NULL, 'Umbrella Policy', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '5', NULL, 'Medical Plan', NULL),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '5', 'A.', 'Medical Plan for yourself', NULL),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '5', 'B.', 'Medical Plan for children', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '6', NULL, 'Dental Plan', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '7', NULL, 'Optical Plan', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '8', NULL, 'Disability', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '9', NULL, 'Worker’s Compensation', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '10', NULL, 'Long Term Care Insurance', 'N/A'),
    ('III.', 'EXPENSES:', '(e)', 'Insurance: Monthly', '11', NULL, 'Other', 'N/A'),
    ('III.', 'EXPENSES:', '(f)', 'Unreimbursed Medical:  Monthly', '1', NULL, 'Medical', NULL),
    ('III.', 'EXPENSES:', '(f)', 'Unreimbursed Medical:  Monthly', '2', NULL, 'Dental', NULL),
    ('III.', 'EXPENSES:', '(f)', 'Unreimbursed Medical:  Monthly', '3', NULL, 'Optical', NULL),
    ('III.', 'EXPENSES:', '(f)', 'Unreimbursed Medical:  Monthly', '4', NULL, 'Pharmaceutical', NULL),
    ('III.', 'EXPENSES:', '(f)', 'Unreimbursed Medical:  Monthly', '5', NULL, 'Surgical, Nursing, Hospital', NULL),
    ('III.', 'EXPENSES:', '(f)', 'Unreimbursed Medical:  Monthly', '6', NULL, 'Psychotherapy', NULL),
    ('III.', 'EXPENSES:', '(f)', 'Unreimbursed Medical:  Monthly', '7', NULL, 'Other', 'N/A'),
    ('III.', 'EXPENSES:', '(g)', 'Household Maintenance:  Monthly', '1', NULL, 'Repairs/Maintenance', 'N/A'),
    ('III.', 'EXPENSES:', '(g)', 'Household Maintenance:  Monthly', '2', NULL, 'Gardening/landscaping', 'N/A'),
    ('III.', 'EXPENSES:', '(g)', 'Household Maintenance:  Monthly', '3', NULL, 'Sanitation/carting', 'N/A'),
    ('III.', 'EXPENSES:', '(g)', 'Household Maintenance:  Monthly', '4', NULL, 'Snow Removal', 'N/A'),
    ('III.', 'EXPENSES:', '(g)', 'Household Maintenance:  Monthly', '5', NULL, 'Extermination', 'N/A'),
    ('III.', 'EXPENSES:', '(g)', 'Household Maintenance:  Monthly', '6', NULL, 'Other', 'N/A'),
    ('III.', 'EXPENSES:', '(h)', 'Household Help:  Monthly', '1', NULL, 'Domestic (housekeeper, etc.)', 'N/A'),
    ('III.', 'EXPENSES:', '(h)', 'Household Help:  Monthly', '2', NULL, 'Nanny/Au Pair/Child Care', 'N/A'),
    ('III.', 'EXPENSES:', '(h)', 'Household Help:  Monthly', '3', NULL, 'Babysitter', 'N/A'),
    ('III.', 'EXPENSES:', '(h)', 'Household Help:  Monthly', '4', NULL, 'Other', 'N/A'),
    ('III.', 'EXPENSES:', '(i)', 'Automobile:  Monthly', '1', NULL, 'Lease or Loan Payments (indicate lease term)', 'N/A'),
    ('III.', 'EXPENSES:', '(i)', 'Automobile:  Monthly', '2', NULL, 'Gas and Oil', NULL),
    ('III.', 'EXPENSES:', '(i)', 'Automobile:  Monthly', '3', NULL, 'Repairs', 'N/A'),
    ('III.', 'EXPENSES:', '(i)', 'Automobile:  Monthly', '4', NULL, 'Car Wash', 'N/A'),
    ('III.', 'EXPENSES:', '(i)', 'Automobile:  Monthly', '5', NULL, 'Parking and tolls', 'N/A'),
    ('III.', 'EXPENSES:', '(i)', 'Automobile:  Monthly', '6', NULL, 'Other', NULL),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '1', NULL, 'Nursery and Pre-school', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '2', NULL, 'Primary and Secondary', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '3', NULL, 'College', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '4', NULL, 'Post-Graduate', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '5', NULL, 'Religious Instruction', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '6', NULL, 'School Transportation', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '7', NULL, 'School Supplies/Books', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '8', NULL, 'School Lunches', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '9', NULL, 'Tutoring', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '10', NULL, 'School Events', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '11', NULL, 'Child(ren)’s extra-curricular and educational enrichment activities (Dance, Music, Sports, etc.)', 'N/A'),
    ('III.', 'EXPENSES:', '(j)', 'Education Costs:  Monthly', '12', NULL, 'Other', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '1', NULL, 'Vacations', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '2', NULL, 'Movies, Theatre, Ballet, Etc.', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '3', NULL, 'Music (Digital or Physical Media)', NULL),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '4', NULL, 'Recreation Clubs and Memberships', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '5', NULL, 'Activities for yourself', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '6', NULL, 'Health Club', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '7', NULL, 'Summer Camp', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '8', NULL, 'Birthday party costs for your child(ren)', 'N/A'),
    ('III.', 'EXPENSES:', '(k)', 'Recreational:  Monthly', '9', NULL, 'Other', 'N/A'),
    ('III.', 'EXPENSES:', '(l)', 'Income Taxes:  Monthly', '1', NULL, 'Federal', 'N/A'),
    ('III.', 'EXPENSES:', '(l)', 'Income Taxes:  Monthly', '2', NULL, 'State', 'N/A'),
    ('III.', 'EXPENSES:', '(l)', 'Income Taxes:  Monthly', '3', NULL, 'City', 'N/A'),
    ('III.', 'EXPENSES:', '(l)', 'Income Taxes:  Monthly', '4', NULL, 'Social Security and Medicare', 'N/A'),
    ('III.', 'EXPENSES:', '(l)', 'Income Taxes:  Monthly', '5', NULL, 'Number of dependents claimed in prior tax year', '0'),
    ('III.', 'EXPENSES:', '(l)', 'Income Taxes:  Monthly', '6', NULL, 'List any refund received by you for prior tax year', NULL),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '1', NULL, 'Beauty parlor/Barber/Spa', NULL),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '2', NULL, 'Toiletries/Non-Prescription Drugs', NULL),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '3', NULL, 'Books, magazines, newspapers', NULL),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '4', NULL, 'Gifts to others', NULL),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '5', NULL, 'Charitable contributions', 'N/A'),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '6', NULL, 'Religious organizations dues', 'N/A'),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '7', NULL, 'Union and organization dues', 'N/A'),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '8', NULL, 'Commutation expenses', 'N/A'),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '9', NULL, 'Veterinarian/pet expenses', NULL),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '10', NULL, 'Child support payments (for Child(ren) of a prior marriage or relationship pursuant to court order or agreement)', 'N/A'),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '11', NULL, 'Alimony and maintenance payments (prior marriage pursuant to court order or agreement)', 'N/A'),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '12', NULL, 'Loan payments', 'N/A'),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '13', NULL, 'Unreimbursed business expenses', NULL),
    ('III.', 'EXPENSES:', '(m)', 'Miscellaneous:  Monthly', '14', NULL, 'Safe Deposit Box rental fee', 'N/A'),
    ('III.', 'EXPENSES:', '(n)', 'Other:  Monthly', '1', NULL, NULL, NULL),
    ('III.', 'EXPENSES:', '(n)', 'Other:  Monthly', '2', NULL, NULL, NULL),
    ('III.', 'EXPENSES:', '(n)', 'Other:  Monthly', '3', NULL, NULL, NULL);