CREATE TABLE teller.transaction_email_candidate (
    candidate_id BIGSERIAL PRIMARY KEY,
    match_run_id BIGINT NOT NULL REFERENCES teller.transaction_email_match_run(match_run_id) ON DELETE CASCADE,
    transaction_id TEXT NOT NULL REFERENCES teller.transaction(transaction_id) ON DELETE CASCADE,
    email_message_id TEXT NOT NULL,
    email_received_at TIMESTAMP WITH TIME ZONE,
    score DECIMAL(5,4) NOT NULL CHECK (score >= 0 AND score <= 1),
    reason_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_unmatched_email_priority BOOLEAN NOT NULL DEFAULT FALSE,
    is_selected_by_ai BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_transaction_email_candidate_transaction_id
    ON teller.transaction_email_candidate(transaction_id);

CREATE INDEX idx_transaction_email_candidate_message_id
    ON teller.transaction_email_candidate(email_message_id);

COMMENT ON TABLE teller.transaction_email_candidate IS 'Candidate emails generated by matchy for a specific run';
