CREATE TABLE IF NOT EXISTS teller.transaction_email_candidate (
    candidate_id BIGSERIAL PRIMARY KEY,
    match_run_id BIGINT NOT NULL REFERENCES teller.transaction_email_match_run(match_run_id) ON DELETE CASCADE,
    transaction_id TEXT NOT NULL REFERENCES teller.transaction(transaction_id) ON DELETE CASCADE,
    email_message_id TEXT NOT NULL,
    email_received_at TIMESTAMP WITH TIME ZONE,
    score DECIMAL(5,4) NOT NULL CHECK (score >= 0 AND score <= 1),
    reason_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_unmatched_email_priority BOOLEAN NOT NULL DEFAULT FALSE,
    is_selected_by_ai BOOLEAN NOT NULL DEFAULT FALSE,
    -- Cached Mailcart metadata so downstream UIs can render subject/sender/snippet without
    -- another per-message Mailcart round-trip per candidate (the Match Review candidates pane
    -- previously paid that round-trip every render, throttling the pane to multi-second loads
    -- whenever the candidate set exceeded ~10 rows due to requests.Session pool limits).
    cached_subject TEXT,
    cached_sender TEXT,
    cached_snippet TEXT,
    cached_fetched_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_transaction_email_candidate_transaction_id
    ON teller.transaction_email_candidate(transaction_id);

CREATE INDEX IF NOT EXISTS idx_transaction_email_candidate_message_id
    ON teller.transaction_email_candidate(email_message_id);

COMMENT ON TABLE teller.transaction_email_candidate IS 'Candidate emails generated by matchy for a specific run';
